name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make assignment1
      run: g++ -std=c++11 -o test_problem1 assignment1/test.cc  -Werror
    - name: make assignement2
      run: g++ -std=c++11 -o test_problem2 assignement2/test.cc  assignement2/largest_sum.cc -Werror 
